version: '3'
services:

  example-application1-api:
    build:
      context: ./example-application1-api
      dockerfile: Dockerfile-dev
    ports:
      - "3080:3080"
    container_name: example-application1-api
    volumes:
       - ./example-application1-api:/usr/src/app/example-application1-api
       - /usr/src/app/example-application1-api/node_modules
    environment: 
      - CHOKIDAR_USEPOLLING=true # <---- this enables the hot reloading
      
  example-application1-vue:
    build:
      context: ./example-application1-vue
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    container_name: example-application1-vue
    volumes:
       - ./example-application1-vue:/usr/src/app/example-application1-vue
       - /usr/src/app/example-application1-vue/node_modules
    environment: 
      - CHOKIDAR_USEPOLLING=true # <---- this enables the hot reloading
