version: '3'
services:

  swagger-ui:
    hostname: swagger-ui
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      - BASE_URL=/
      - SWAGGER_JSON=/apis/api-doc.yml
      - ENABLE_CORS=true
    volumes:
      - ./swagger-ui/:/apis
    ports:
      - "5014:8080"

  example-application1-api:
    build:
      context: ./example-application1-api
      dockerfile: Dockerfile-dev
    hostname: api

    ports:
      - "3080:3080"
    container_name: example-application1-api
    volumes:
       - ./example-application1-api:/usr/src/app/example-application1-api
       - /usr/src/app/example-application1-api/node_modules
    environment: 
      - CHOKIDAR_USEPOLLING=true # <---- this enables the hot reloading
      
  example-application1-vue:
    build:
      context: ./example-application1-vue
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    container_name: example-application1-vue
    volumes:
       - ./example-application1-vue:/usr/src/app/example-application1-vue
       - /usr/src/app/example-application1-vue/node_modules
    environment: 
      - CHOKIDAR_USEPOLLING=true # <---- this enables the hot reloading

networks:
  default:
    external:
      name: we-settle
