const Permission = {
  USER_UPDATE: "USER_UPDATE",
  USER_CREATE: "USER_CREATE",
  USER_DELETE: "USER_DELETE",
  USER_LIST: "USER_LIST",
  USER_DETAILS: "USER_DETAILS",

  ROLE_UPDATE: "ROLE_UPDATE",
};

module.exports = Permission;
